apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-data-web
  namespace: open-data-app
  labels:
    app: open-data-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-data-web
  template:
    metadata:
      labels:
        app: open-data-web
    spec:
      containers:
        - name: open-data-web
          image: open-data-web:gitops
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: GITOPS_MESSAGE
              value: "GitOps version 1 - deployed by Argo CD"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20